# Generated by Django 4.0.5 on 2022-07-16 12:42

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path

DATA_FILE = 'data_points.json'

class Migration(migrations.Migration):
    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
                  ]
def data_loading_function(apps, schema_editor):
    Trip = apps.get_model('trips', 'Trip')

    with open("D:/djangoapp_toruntrip/toruntrip/toruntrip/data_points.json",encoding="utf8") as obj_data:
        loaded_data = json.load(obj_data)
        for i in loaded_data['elements']:
            try:
                type_object = i['elements'][0]['type']
                if type_object == 'node':
                    tags = i['elements'][0]['tags']
                    name = tags.get('name')
                    longitude = i['elements'].get('lon', 0)
                    latitude = i['elements'].get('lat', 0)
                    adress_street = tags.get('addr:street')
                    adress_housenumber = tags.get('addr:housenumber')
                    adress = adress_street + adress_housenumber
                    if tags.get('historic') != "":
                        description = tags.get('historic')
                    else:
                        description = ""
                    location = fromstr(f'POINT({longitude} {latitude})', srid=4326)
                    Trip(name=name, location=location,adress=adress,description=description).save()
            except KeyError:
                pass

